Use platform error_prone_annotations
add it to dialer-rootcomponentprocessor.

The jdk-11.0.13 update triggers an error in the errorprone build:
error: cannot access CompatibleWith
  class file for errorprone.annotations.CompatibleWith not found

Add error_prone_annotations to the dialer-rootcomponentprocessor
dependencies, and replace the other usages of dialer-error-prone-target
in the file to match.

Bug: 205944740
Test: m RUN_ERROR_PRONE=true out/host/common/obj/JAVA_LIBRARIES/
dialer-rootcomponentprocessor_intermediates/classes-full-debug.jar
Change-Id: Ic6cf6614e522919b793744313adfd4c8763b4b61
(cherry picked from commit 7a4f978b2bb2ffdba4c9b6730ada42fbdd0281b7)

CRs-Fixed: 3361397